name: Coleta Automatica de Dados

on:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6 horas
  workflow_dispatch: # Permite rodar manualmente pelo site do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install requests pandas python-dotenv

      - name: Executar coletor
        env:
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
        run: python src/coletor.py

      - name: Salvar alteracoes no repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/historico_ar.csv
          git commit -m "Atualizacao automatica: $(date)" || exit 0
          git push